### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by Shivraj97** [yosevu/react-content-script#13]
Hi, I cloned the repo and did npm install and npm run dev and was able to load the extension but as CRX promised that it can hot reload both the content script and popup script but it's not doing so or do I have to build every time I make change to source code ? Can you please help.

**Comment by yosevu** [comment]
Hi @Shivraj97, I'll take a look!

**Comment by Norfeldt** [comment]
Perhaps using nodemon to trigger a rebuild on save could be one way of going about it?

https://www.npmjs.com/package/nodemon

**Comment by yosevu** [comment]
Hmm, it looks like other people have this issue too: https://github.com/crxjs/chrome-extension-tools/issues/515. Will try updating the dependency as suggested.

**Comment by yosevu** [comment]
Sorry for the delay @Shivraj97, but I updated the crxjs vite-plugin version, which fixed `yarn dev`. content-script and popup HMR work as expected. Make sure that you are making changes and looking at the correct app i.e. popup src in the extension popup window and content-script src on blank.org etc.
