### ISSUE TITLE
using TailwindCSS for styling

### ISSUE THREAD

**Issue by nkilm** [yosevu/react-content-script#16]
### Description

**How to add [TailwindCSS](https://tailwindcss.com/) to both content-script and popup html?** I've tried installing Tailwind by referring the offical [docs](https://tailwindcss.com/docs/guides/create-react-app) but the CSS is not getting applied. Any help would be appreciated.

**Comment by yosevu** [comment]
Hi @nkilm, I'll take a look at this and let you know!

**Comment by yosevu** [comment]
Is this the setup you wanted @nkilm?

I created an example in Popup src:

https://github.com/yosevu/react-content-script/pull/17

**Comment by nkilm** [comment]
@yosevu Yes similar setup, but the example #17 you provided is not working for popup. 

The tailwind classes are not applied to the popup,
```tsx
/// <reference types="chrome" />
/// <reference types="vite-plugin-svgr/client" />

import Logo from "./Logo";
import "./App.css";

function App() {
  return (
    <div className="App">
      <header className="bg-gray-800 min-h-screen flex flex-col items-center justify-center text-white text-lg">
		// the above classes are not applied
        <Logo className="App-logo" id="App-logo" title="React logo" />
        <p>Hello, World!</p>
        <p>I'm a Chrome Extension Popup!</p>
      </header>
    </div>
  );
}

export default App;
```

e.g - `bg-gray-800` should make the bg gray colored

![image](https://user-images.githubusercontent.com/79012023/224557994-107b00cb-d31e-4c65-b27f-3c73d7aaf05f.png)

**Comment by yosevu** [comment]
Did you run `yarn build` and reload the extension from `dist` @nkilm?

This is what I see:

<img width="1440" alt="Screen Shot 2023-03-12 at 2 06 12 PM" src="https://user-images.githubusercontent.com/16216104/224567001-49783f05-923b-456b-b613-eb9c34eafd9e.png">

**Comment by nkilm** [comment]
@yosevu Ah it worked after I removed and added the extension with recent changes. Thank you so much Yosefu!✨
