### ISSUE TITLE
how can make content script to be hot reload?

### ISSUE THREAD

**Issue by zhuliminl** [yosevu/react-content-script#20]

**Comment by Toumash** [comment]
Should work by default with crxjs@beta

**Comment by devlopersabbir** [comment]
You can use this extension [Extensions Reloader](https://chromewebstore.google.com/detail/extensions-reloader/fimgfedafeadlieiabdeeaodndnlbhid?hl=en), I'm using this extension more then 2 years. 🙂

**Comment by Toumash** [comment]
For some reason:

![image](https://github.com/user-attachments/assets/f38b817d-4156-4fca-b4c5-02db9a978966)
> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.


crxjs@beta (currently 25 patch version) works perfecly with hot reload.
For the hot reload (hot module replacement) to work with vite you need to have file export only one component. To remember this you can use eslint rule: https://github.com/ArnaudBarre/eslint-plugin-react-refresh

**Comment by yosevu** [comment]
HMR should work in latest version. See https://crxjs.dev/vite-plugin/getting-started/react/content-script-hmr for instructions.
