### ISSUE TITLE
Use Vite instead of CRA?

### ISSUE THREAD

**Issue by Norfeldt** [yosevu/react-content-script#5]
thank you very much for sharing this repo with the world 🙏

I found it really useful when developing a chrome extension. I decided to change it so that uses Vite instead of Create React App and use TypeScript (which is also possible with CRA). Would you be interested in getting a PR for replacing CRA with Vite?

**Comment by yosevu** [comment]
Hi @Norfeldt, sure that would be great to see!

**Comment by Norfeldt** [comment]
done with #6
