### ISSUE TITLE
Error while using material ui.

### ISSUE THREAD

**Issue by anamgajith** [yosevu/react-content-script#9]
Hey Yosevu,

Thank you for creating this awesome template, when I am trying to build the app after using material ui it's giving some build errors, can you please check this issue.

**Comment by yosevu** [comment]
Hi @anamgajith, could you give an example of the errors you are seeing or how to reproduce the issue with Material UI. Thanks!

**Comment by yosevu** [comment]
Feel free to reopen this if you want to revisit the issue @anamgajith.
